### ISSUE TITLE
cli tool broken?

### ISSUE THREAD

**Issue by martijnthe** [gmr/hockeyapp#10]
```
$ hockeyapp-cli -k *REDACTED* list-applications
Traceback (most recent call last):
  File "/usr/local/bin/hockeyapp-cli", line 9, in <module>
    load_entry_point('hockeyapp==0.4.0', 'console_scripts', 'hockeyapp-cli')()
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/hockeyapp-0.4.0-py2.7.egg/hockeyapp/cli.py", line 168, in main
    args.func(args)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/hockeyapp-0.4.0-py2.7.egg/hockeyapp/cli.py", line 61, in <lambda>
    show(apps.AppList(a.api_key)))
NameError: global name 'apps' is not defined
```

**Comment by vkotovv** [comment]
Just created a pull request for this - #17
